### ISSUE TITLE
Cannot load plugin - classFactory() error

### ISSUE THREAD

**Issue by merkato** [3liz/lizmap-plugin#394] opened 2021-12-22 19:04 UTC
Can't install latest Lizmap plugin version in fresh Windows/QGIS installation. 
After updating 3.4.4 (working) to latest in Ubuntu 20.04, same error arises.

```
Nie można wczytać wtyczki 'lizmap' z powodu błędu wywołania jej metody classFactory() 

KeyError: 'wersja' 
Traceback (most recent call last):
  File "D:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/tomas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\__init__.py", line 56, in classFactory
    return Lizmap(iface)
  File "C:\Users/tomas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lizmap\plugin.py", line 549, in __init__
    self.dlg.qgis_and_lwc_versions_issue.setText(text.format(version=current))
KeyError: 'wersja'

Wersja Pythona: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Wersja QGIS: 3.22.1-Białowieża Białowieża, 663dcf8fb9 
```

https://github.com/3liz/lizmap-plugin/blob/c46c0a61892e6083f979ace815512800ee9b2dea/lizmap/plugin.py#L549

**Comment by Gustry** [comment] 2021-12-22 20:38
Duplicate of #393

**Closed by Gustry** 2021-12-22 20:38 UTC
