### ISSUE TITLE
More consistent behaviour for the "single tile" and "server tile cache" checkboxes

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-plugin#500] opened 2023-06-02 10:54 UTC
At the moment:

*) if  "server tile cache" is checked, then checking "single tile" it unchecks "server tile cache" > OK

*) if  "single tile" is checked then to check  "server tile cache" is first necessary to uncheck "single tile" > not ok, because is not consistent wit the first case and also because this can leave a layer with both "single tile" and "server tile cache" unchecked

**Comment by Gustry** [comment] 2023-06-02 12:07
> *) if "server tile cache" is checked, then checking "single tile" it unchecks "server tile cache" > OK

Correct, indeed, it's not possible to have "single tile" with a cache on the server side. That's why is not only unchecked, but also disabled/greyed.

>  this can leave a layer with both "single tile" and "server tile cache" unchecked

Because it's possible, you can ask multiple tiles (not single tile), but without making them cached on the server side. So both checkbox must be unchecked.

**Comment by gioman** [comment] 2023-06-02 12:46
> Because it's possible, you can ask multiple tiles (not single tile), but without making them cached on the server side. So both checkbox must be unchecked.

@Gustry good to know, I wasn't aware it was a possibility.

**Comment by Gustry** [comment] 2023-07-11 10:46
As it's only a UX issue, I'm closing as this ticket is a duplicate of #248

**Closed by Gustry** 2023-07-11 10:46 UTC
Labels: Feature Request
