### ISSUE TITLE
 If the third party wms is not available, it blocks the loading of the Lizmap project

### ISSUE THREAD

**Issue by RacheleVaracalli** [3liz/lizmap-plugin#415] opened 2022-05-04 15:09 UTC
Hello,
I'm detecting a problem with a Lizmap project created with Qgis. If there is a third part WMS in the project and this WMS is temporarily unavailable the entire project is not loaded.

Thanks.

* QGIS version:  3.10.4 (client and server ) 
* Lizmap version: 3.4.8
* OS: Windows 10

**Comment by pcav** [comment] 2022-05-04 15:57
Known issue, confirmed and true since long.
One possible workarouind is to cache the wms.

**Comment by RacheleVaracalli** [comment] 2022-05-05 06:17
Thank you so much for reply,but unfortunately for me the cache option is disable.

![image](https://user-images.githubusercontent.com/99020496/166871279-7d2d8b4e-df03-4661-8b50-8c4313222d2a.jpg)

**Comment by Gustry** [comment] 2022-05-05 07:04
Your initial issue about WMS is not related to Lizmap, but related to QGIS Server.
You could add the `QGIS_SERVER_IGNORE_BAD_LAYERS` but this won't resolve the issue completely when the server is slow to respond.
On our hosting infrastructure, we are setting up different kind of caching to overcome issues like this.

For your screenshot above, this is because of the "single tile" being checked.

**Comment by RacheleVaracalli** [comment] 2022-05-05 07:30
Ok perfect, now everything is clearer.I didn't set the options correctly.
 I'll also try to set the QGIS_SERVER_IGNORE_BAD_LAYERS variable.
Thank you very much everyone for the support.

**Comment by Gustry** [comment] 2022-05-05 08:21
Caching might be a complex topic as there are  different strategies, level etc.

I'm closing the ticket for now :)

**Closed by Gustry** 2022-05-05 08:21 UTC
Labels: Question, Feedbacks
