### ISSUE TITLE
snapping options - inverted tip

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-plugin#327] opened 2020-12-28 11:11 UTC
the tips are reversed, regarding delete and edit options

![snap](https://user-images.githubusercontent.com/10053874/103210121-b4f75a80-48fc-11eb-831a-36815815b36e.png)

* QGIS version: 3.3.10
* Lizmap version: 3.4
* OS:

**Comment by Gustry** [comment] 2020-12-28 11:48
Duplicate of https://github.com/3liz/lizmap-plugin/issues/323

**Closed by Gustry** 2020-12-28 11:48 UTC
Labels: Bug
